/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const RegisterLazyImport = createFileRoute('/register')()
const PrivateMessagesLazyImport = createFileRoute('/private-messages')()
const LoginLazyImport = createFileRoute('/login')()
const GeneralChatLazyImport = createFileRoute('/general-chat')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const RegisterLazyRoute = RegisterLazyImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))

const PrivateMessagesLazyRoute = PrivateMessagesLazyImport.update({
  path: '/private-messages',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/private-messages.lazy').then((d) => d.Route),
)

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const GeneralChatLazyRoute = GeneralChatLazyImport.update({
  path: '/general-chat',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/general-chat.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/general-chat': {
      preLoaderRoute: typeof GeneralChatLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/private-messages': {
      preLoaderRoute: typeof PrivateMessagesLazyImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      preLoaderRoute: typeof RegisterLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  GeneralChatLazyRoute,
  LoginLazyRoute,
  PrivateMessagesLazyRoute,
  RegisterLazyRoute,
])

/* prettier-ignore-end */
